### PR TITLE
refactor: cleanup pdf page load check

### PR DESCRIPTION
**Pull request by albinekb**

### CODE REVIEW

**Comment by adieuadieu** [comment]
Hi @albinekb, I apologize for my slow reply! I've been away from my computer the past few days. Thank you for the improvements! I'll merge them this week.

**Comment by adieuadieu** [comment]
Thanks again for this PR, @albinekb. Your refactor is great. Makes me realise how silly my implementation was!

**Comment by adieuadieu** [comment]
There's a rework going on in feature/v1.0 branch where the Serverless-framework code is moved into a separate function examples folder. There, the printToPdf Lambda handler has been updated to include a request queue. If you're interested, perhaps you could apply your improvements there, too? Unfortunately, it's all still a bit of a mess—so not super straightforward to make the contribution. For example, my goal is to keep the Serverless-framework example very simple, which means avoiding non Node 6.10 features that require an extra transpilation step or plugins (e.g. async-await 😭 .) That means, [printToPdf.js](https://github.com/adieuadieu/serverless-chrome/blob/feature/v1.0/functions/serverless-framework/src/printToPdf.js) needs to be refactored.

**Comment by albinekb** [comment]
Will do @adieudieu, maybe use async-to-gen?

**Comment by adieuadieu** [comment]
Hm.. I'd like to keep the example functions simple or easy to understand, even for more novice developers. I feel that perhaps generators aren't the easiest thing for some to understand. I'd love to keep async-await.. But, to reduce the complexity of the examples, I'd like to avoid any sort of build or transpilation steps for the Serverless-framework functions.. So we're left with just using Promises and some chain of thenables.. Certainly not ideal. What do you think?

**Comment by albinekb** [comment]
Yeah, that's good reasoning. Let's keep it to the node 6 stuff, and pray for AWS to upgrade to node 8 soon 👼  which should happen this year. I'll send a PR over later 👌

**Pull request merged**
