### PR TITLE
fix(webpackLocal): fixing this.webpack always true in configuration

### PR DESCRIPTION
**Pull request by wilau2**
switching keys as suggested in #104 

published a quick fix version to unblocked people who want's to use this locally 
@tcollins
@cirdes
@nerdmax
image

### CODE REVIEW

**Comment by thomaschaaf** [comment]
Is there a reason this is not merged yet? Manually applying this fix makes the plugin work locally.

**Comment by wilau2** [comment]
Hey @thomaschaaf, feel free to use the version I deployed for ease of use. 
This PR. is based on another PR that never got merged. I tried applying the changes request by @adieuadieu in pull request #104.

**Comment by onoranzefunebricloud** [comment]
Can we merge this?

**Comment by adieuadieu** [comment]
Published in serverless-plugin-chrome@1.0.0-55.3

**Pull request merged**
