### PR TITLE
Omit default chrome flags when using local launcher

### PR DESCRIPTION
**Pull request by benjaminwood**
When using `chrome-launcher` locally/in development, it's unlikely that people want the default flags to be passed. For example, if you want to load chrome in normal/non-headless-mode the flag `--single-process` will break things.

Thoughts?

### CODE REVIEW

**Comment by adieuadieu** [comment]
Hi @benjaminwood Thank you for the PR. You bring up a good point. My biggest concern with disabling the default flags is that it makes the behaviour of Chrome between Lambda and Local quite different. I'd rather this somehow be very explicit to the developer. However, after playing with the flags some more with Chrome Canary.. The lambda/headless-related flags kind of make Canary useless as a local development tool. Perhaps the best thing to do, then, is to make it clear in the documentation concerning local development, that the behaviour of Chrome is not be identical. There's a section about local development in both `@serverless-chrome/lambda` [README](https://github.com/adieuadieu/serverless-chrome/tree/develop/packages/lambda#local-development) and `serverless-plugin-chrome`'s [README](https://github.com/adieuadieu/serverless-chrome/tree/develop/packages/serverless-plugin#local-development). Is this something you could tackle in this PR? No problem if you can't.

**Comment by benjaminwood** [comment]
@adieuadieu cool so to confirm the plan:

Update both readmes with a disclaimer that the behavior of chrome does vary between platforms. It may be necessary to experiment with flags to get consistent results. 

It may be worth listing what flags are passed to chrome on lambda, and making it clear that those flags are not passed by default in local development. Thoughts on that?

**Comment by adieuadieu** [comment]
Hi @benjaminwood Yes; that's correct. Also, listing the flags which are omitted during dev is a good idea. That makes it very clear up front without the need for someone to have to go dig through the code.

**Comment by adieuadieu** [comment]
Hi @benjaminwood would you still be interest in completing this PR?

**Comment by benjaminwood** [comment]
Hey @adieuadieu yes I'd still like to complete this. I apologize for the delay! Hoping to get to it this week.

**Comment by benjaminwood** [comment]
@adieuadieu I've added a note to both readmes in the local development section. I linked directly to the default [flags file](https://github.com/adieuadieu/serverless-chrome/blob/develop/packages/lambda/src/flags.js) instead of listing them in line as I'm sure the default flags will change over time and we do not want the readme to fall behind.

Let me know what you think and if there are any revisions I can make.

**Pull request merged**
