### PR TITLE
feat: add support for packaging individually in serverless-plugin

### LINKED ISSUE #82: Support for packaging individually in serverless-plugin
I get this error when using webpack (yes it's after serverless chrome) or packaging individually without webpack using:
```
package:
    individually: true
```
I'm not sure whats up but i'll look into it more. Likely the artifact path isn't stored where it's expected when packaging separately.

Any ideas?

```
  Type Error ---------------------------------------------

  Path must be a string. Received undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at /Users/kyle/development/serverless-capture/node_modules/serverless-plugin-chrome/dist/index.js:196:116
    at next (native)
    at step (/Users/kyle/development/serverless-capture/node_modules/serverless-plugin-chrome/dist/index.js:58:194)
    at /Users/kyle/development/serverless-capture/node_modules/serverless-plugin-chrome/dist/index.js:58:367
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:366:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:397:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:104:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:91:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:42:50)
```

### LINKED ISSUE #155: Error on deploy after "Serverless: Injecting Headless Chrome..."
I am getting an error on deployment of the service right after the info `Serverless: Injecting Headless Chrome...`. Error is:
```
Error --------------------------------------------------

  ENOENT: no such file or directory, unlink '/home/user/application/service/.build/handler.js'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------
```

There is no .build or handler.js and I have no idea why it would assume that there is as there is zero configuration to that effect.

### PR DESCRIPTION
**Pull request by adieuadieu**
Closes #82 
Closes #155

### CODE REVIEW

**Comment by aymericbouzy** [comment]
Thank you so much @adieuadieu 🙏

**Comment by erdahuja** [comment]
Will it support node10.x runtime of lambda now? I tried this plugin it says only node6.10 or node8.10.

**Comment by adieuadieu** [comment]
@erdahuja it's coming.

**Comment by barnettx** [comment]
Hi @adieuadieu 

this commit doesn't appear if I try installing this plugin via npm. I have tried reinstalling as well.

when looking at the registry link: [https://registry.npmjs.org/serverless-plugin-chrome/-/serverless-plugin-chrome-1.0.0-55.tgz] it seems like the old index.js is still being used.

perhaps a version increment will help to re-package. Should I open a separate issue for this?

Thanks

**Pull request merged**
