### PR TITLE
AWS lambda runtime deprecations

### PR DESCRIPTION
**Pull request by evgeniyannenkov**
re #244

### CODE REVIEW

**Comment by onoranzefunebricloud** [comment]
Does this library already work with node 10? Or is this PR needed before it can actually work?

**Comment by evgeniyannenkov** [comment]
@onoranzefunebricloud it will work with node 10.x 12.x only after this pr will be merged

**Comment by onoranzefunebricloud** [comment]
Thanks @evgeniyannenkov! I am struggling setting this up with Node 10, I'd really love to see this merge then!

**Comment by onoranzefunebricloud** [comment]
@evgeniyannenkov what about the `SUPPORTED_RUNTIMES` array?

**Comment by 00dev** [comment]
> @evgeniyannenkov what about the `SUPPORTED_RUNTIMES` array?

It's already changed in version v1.0.0-55.1

**Comment by onoranzefunebricloud** [comment]
Sorry, I didn't see it. Thanks both. Ping me if you need reviews or PRs next time, happy to contribute.

**Comment by evgeniyannenkov** [comment]
@adieuadieu Any chance you can merge this so the project could run with 12.x node? Also the version patch is needed too.

Thanks

**Comment by adieuadieu** [comment]
Thank you, @evgeniyannenkov 

Published in serverless-plugin-chrome@1.0.0-55.2

**Comment by khacminh** [comment]
Hi @adieuadieu  I tried with serverless-plugin-chrome@1.0.0-55.3 and it doesn't work with node.js 12.x

**Comment by melnychuka** [comment]
Hi @adieuadieu! When this will be merged to master?

**Pull request merged**
